[project]
name = ""
version = "1.0.4"
requires-python = ">=3.13"
dependencies = [
    "lxml>=4.6.1",
    "pygame-ce>=2.0.0",
    "pygame-popup==0.11.2",
    "pytest>=9.0.0",
    "pytmx>=3.31",
]

[tool.uv]
package = false
